import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/frontend/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#f7f3ed',
        'on-surface': '#1c1c18',
        'surface-variant': '#e6e2dc',
        'on-secondary': '#ffffff',
        'on-background': '#1c1c18',
        'on-tertiary-fixed-variant': '#574500',
        'on-surface-variant': '#564244',
        'on-error': '#ffffff',
        'surface-container-highest': '#e6e2dc',
        'on-tertiary-container': '#4f3e00',
        primary: '#6c0c28',
        'surface-dim': '#dddad4',
        'on-secondary-fixed': '#380a16',
        'on-primary-container': '#ffa3b0',
        'on-primary': '#ffffff',
        'surface-tint': '#a3394f',
        'on-secondary-container': '#7a3f4a',
        'inverse-surface': '#31302d',
        'on-tertiary-fixed': '#241a00',
        'on-tertiary': '#ffffff',
        background: '#fdf9f3',
        'surface-container-high': '#ebe8e2',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffd9dd',
        tertiary: '#735c00',
        'on-primary-fixed': '#400013',
        secondary: '#8a4c57',
        error: '#ba1a1a',
        'inverse-primary': '#ffb2bc',
        'inverse-on-surface': '#f4f0ea',
        surface: '#fdf9f3',
        'outline-variant': '#dcc0c2',
        'tertiary-fixed-dim': '#e9c349',
        'error-container': '#ffdad6',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed': '#ffe088',
        'secondary-container': '#fdafbb',
        'secondary-fixed': '#ffd9de',
        'primary-fixed-dim': '#ffb2bc',
        'surface-bright': '#fdf9f3',
        'primary-container': '#8b263e',
        'on-primary-fixed-variant': '#842039',
        outline: '#897174',
        'tertiary-container': '#cca830',
        'surface-container': '#f1ede7',
        'secondary-fixed-dim': '#ffb2be',
        'on-secondary-fixed-variant': '#6e3540',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      animation: {
        'spin-slow': 'spin 4s linear infinite',
      },
      fontFamily: {        // Playfair Display — para títulos
        'display-lg':        ['var(--font-playfair)', 'Georgia', 'serif'],
        'headline-lg':       ['var(--font-playfair)', 'Georgia', 'serif'],
        'headline-md':       ['var(--font-playfair)', 'Georgia', 'serif'],
        'headline-sm':       ['var(--font-playfair)', 'Georgia', 'serif'],
        'headline-lg-mobile':['var(--font-playfair)', 'Georgia', 'serif'],
        'display-lg-mobile': ['var(--font-playfair)', 'Georgia', 'serif'],
        // Plus Jakarta Sans — para cuerpo
        'body-lg':    ['var(--font-jakarta)', 'sans-serif'],
        'body-md':    ['var(--font-jakarta)', 'sans-serif'],
        'body-sm':    ['var(--font-jakarta)', 'sans-serif'],
        'label-lg':   ['var(--font-jakarta)', 'sans-serif'],
        'label-md':   ['var(--font-jakarta)', 'sans-serif'],
        'label-sm':   ['var(--font-jakarta)', 'sans-serif'],
      },
      fontSize: {
        'label-sm':           ['11px', { lineHeight: '14px', letterSpacing: '0.08em',  fontWeight: '500' }],
        'body-lg':            ['18px', { lineHeight: '28px',  fontWeight: '400' }],
        'headline-lg':        ['40px', { lineHeight: '48px',  letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-lg':           ['14px', { lineHeight: '20px',  letterSpacing: '0.04em',  fontWeight: '600' }],
        'body-md':            ['16px', { lineHeight: '24px',  fontWeight: '400' }],
        'headline-sm':        ['22px', { lineHeight: '30px',  fontWeight: '600' }],
        'display-lg':         ['56px', { lineHeight: '64px',  letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-sm':            ['14px', { lineHeight: '20px',  fontWeight: '400' }],
        'headline-md':        ['28px', { lineHeight: '36px',  fontWeight: '500' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px',  letterSpacing: '0',       fontWeight: '600' }],
        'display-lg-mobile':  ['38px', { lineHeight: '46px',  letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-md':           ['12px', { lineHeight: '16px',  letterSpacing: '0.06em',  fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};

export default config;
